# -*- coding: utf-8 -*-
"""Inventario canónico de writers de stock (Fase 0 + re-inventario 1E.0).

El scanner de `test_stock_writers.py` (y `tests/fase1e`) falla si aparece un
UPDATE/INSERT directo de `productos.stock` que no esté listado.

Ninguna de estas rutas es la autoridad futura. W01–W18 mutan la proyección
local en legacy. D05 proyecta caché tras APPLIED. Cutover 1E.3 implementa
el mecanismo; el default de fuente sigue OFF.
"""
from __future__ import annotations

from typing import FrozenSet, Tuple

# ---------------------------------------------------------------------------
# Inventario declarado (1E.0). Cada fila = un writer o un derivado.
# classification: NEGATIVO | POSITIVO | MIXTO | DERIVADO
# ---------------------------------------------------------------------------

STOCK_WRITERS: Tuple[dict, ...] = (
    {
        "id": "W01",
        "file": "repositories/compras_repo.py",
        "function": "ComprasRepository.crear_compra",
        "business": "compra a proveedor",
        "sign": "+",
        "classification": "POSITIVO",
        "sql": "stock = stock + ?",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "movimientos.ENTRADA_COMPRA",
        "outbox": True,
        "offline_possible": True,
        "callers": ("ui/compras_ui.py",),
        "risk": "Tercer camino de ingreso (INV-03) junto a movimientos e inventario.",
        "kind": "direct",
    },
    {
        "id": "W02",
        "file": "repositories/compras_repo.py",
        "function": "ComprasRepository.eliminar_compra",
        "business": "cancelar compra (marca CANCELADA)",
        "sign": "-",
        "classification": "NEGATIVO",
        "sql": "stock = stock - ?  (sin stock>=)",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "movimientos.SALIDA_AJUSTE (asiento nuevo, no borra ENTRADA_COMPRA)",
        "outbox": True,
        "offline_possible": True,
        "callers": (),
        "risk": "Cero llamadores de UI. Sin piso stock>=. Puede ir negativo.",
        "kind": "direct",
    },
    {
        "id": "W03",
        "file": "services/ventas_service.py",
        "function": "VentasService.registrar_venta",
        "business": "venta POS escritorio",
        "sign": "-",
        "classification": "NEGATIVO",
        "sql": "stock = stock - ? WHERE stock >= ?",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "movimientos.SALIDA_VENTA",
        "outbox": True,
        "offline_possible": True,
        "callers": ("ui/ventas_ui_modern.py",),
        "risk": "Guard local; no serializa dos SQLite (INV-01). Mezclas de pintura "
                "también descuentan por aquí (componentes), no por W15.",
        "kind": "direct",
    },
    {
        "id": "W04",
        "file": "services/ventas_service.py",
        "function": "VentasService.cancelar_venta",
        "business": "cancelar venta persistida",
        "sign": "+",
        "classification": "POSITIVO",
        "sql": "stock = stock + ?",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "movimientos.ENTRADA_DEVOLUCION",
        "outbox": True,
        "offline_possible": True,
        "callers": (),
        "risk": "ui/ventas_ui_modern.cancelar_venta solo vacía el carrito; no llama "
                "este método. Código vivo sin caller de UI.",
        "kind": "direct",
    },
    {
        "id": "W05",
        "file": "services/ventas_service.py",
        "function": "VentasService.registrar_devolucion",
        "business": "devolución total/parcial",
        "sign": "+",
        "classification": "POSITIVO",
        "sql": "stock = stock + ?",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "movimientos.ENTRADA_DEVOLUCION",
        "outbox": True,
        "offline_possible": True,
        "callers": (),
        "risk": "Tablas devoluciones/devolucion_detalle fuera de SYNC_REGISTRY. "
                "Sin caller de UI encontrado.",
        "kind": "direct",
    },
    {
        "id": "W06",
        "file": "services/ventas_service.py",
        "function": "VentasService.agregar_productos_a_factura",
        "business": "añadir líneas a factura crédito",
        "sign": "-",
        "classification": "NEGATIVO",
        "sql": "stock = stock - ?  (sin stock>=)",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "movimientos.SALIDA_VENTA",
        "outbox": True,
        "offline_possible": True,
        "callers": ("ui/ventas_ui_modern.py", "ui/dashboard_ui.py"),
        "risk": "Check de stock previo no atómico; puede ir negativo.",
        "kind": "direct",
    },
    {
        "id": "W07",
        "file": "repositories/productos_repo.py",
        "function": "ProductosRepository.actualizar_stock",
        "business": "ajuste genérico sumar/restar",
        "sign": "+/-",
        "classification": "MIXTO",
        "sql": "SET stock = ? (calculado)",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": None,
        "outbox": True,
        "offline_possible": True,
        "callers": (),
        "risk": "Sin kardex. Cero llamadores. Restar tiene piso <0 en Python, no SQL.",
        "kind": "direct",
    },
    {
        "id": "W08",
        "file": "repositories/productos_repo.py",
        "function": "ProductosRepository.actualizar_producto",
        "business": "editar ficha de producto",
        "sign": "+/- (valor absoluto de ficha)",
        "classification": "MIXTO",
        "sql": "SET stock = ? (valor de ficha)",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": None,
        "outbox": True,
        "offline_possible": True,
        "callers": ("ui/productos_ui.py",),
        "risk": "LWW de stock al editar cualquier campo. Sin kardex.",
        "kind": "direct",
    },
    {
        "id": "W09",
        "file": "repositories/productos_repo.py",
        "function": "ProductosRepository.crear_producto",
        "business": "alta de SKU",
        "sign": "+ (INSERT; 0 o N)",
        "classification": "POSITIVO",
        "sql": "INSERT INTO productos (... stock ...)",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "movimientos.ENTRADA_AJUSTE si stock>0",
        "outbox": True,
        "offline_possible": True,
        "callers": ("ui/productos_ui.py",),
        "risk": "Producto nuevo puede nacer con stock>0 (viola recepción futura).",
        "kind": "insert",
    },
    {
        "id": "W10",
        "file": "services/movimientos_service.py",
        "function": "MovimientosService.registrar_movimiento",
        "business": "kardex movimientos (incluye ENTRADA_COMPRA)",
        "sign": "+/- según tipo ENTRADA*/SALIDA*",
        "classification": "MIXTO",
        "sql": "SET stock = ?",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "movimientos",
        "outbox": True,
        "offline_possible": True,
        "callers": ("ui/movimientos_ui.py",),
        "risk": "Segundo camino de ENTRADA_COMPRA (INV-03). Salida verifica stock en Python.",
        "kind": "direct",
    },
    {
        "id": "W11",
        "file": "services/movimientos_service.py",
        "function": "MovimientosService.anular_movimiento",
        "business": "anular movimiento de kardex",
        "sign": "+/- (inverso del original)",
        "classification": "MIXTO",
        "sql": "SET stock = ?",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "UPDATE observaciones [ANULADO]; no borra fila",
        "outbox": True,
        "offline_possible": True,
        "callers": (),
        "risk": "Cero llamadores de UI. Piso <0 en Python.",
        "kind": "direct",
    },
    {
        "id": "W12",
        "file": "repositories/inventario_repository.py",
        "function": "InventarioRepository.registrar_movimiento",
        "business": "segundo kardex movimientos_inventario",
        "sign": "+/- según tipo ENTRADA*/SALIDA*",
        "classification": "MIXTO",
        "sql": "SET stock = ?",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "movimientos_inventario (incluye ENTRADA_COMPRA)",
        "outbox": True,
        "offline_possible": True,
        "callers": ("ui/entrada_inventario_ui.py",),
        "risk": "Tercer camino de ENTRADA_COMPRA (INV-03).",
        "kind": "direct",
    },
    {
        "id": "W13",
        "file": "repositories/inventario_repository.py",
        "function": "InventarioRepository.ajustar_stock_directo",
        "business": "inventario físico / corrección",
        "sign": "+/- (delta a valor absoluto)",
        "classification": "MIXTO",
        "sql": "SET stock = ?",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "movimientos_inventario ENTRADA_AJUSTE/SALIDA_AJUSTE",
        "outbox": True,
        "offline_possible": True,
        "callers": (),
        "risk": "Cero llamadores de UI. Pisa stock a un entero arbitrario.",
        "kind": "direct",
    },
    {
        "id": "W14",
        "file": "repositories/inventario_repository.py",
        "function": "InventarioRepository.eliminar_movimiento",
        "business": "borrar movimiento_inventario y revertir",
        "sign": "+/- (inverso si revertir_stock=True)",
        "classification": "MIXTO",
        "sql": "SET stock = ?",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "DELETE movimientos_inventario",
        "outbox": True,
        "offline_possible": True,
        "callers": (),
        "risk": "Cero llamadores de UI. Piso <0 en Python.",
        "kind": "direct",
    },
    {
        "id": "W15",
        "file": "services/mezclas_service.py",
        "function": "MezclasService.descontar_stock_mezcla",
        "business": "consumo de componentes de mezcla",
        "sign": "-",
        "classification": "NEGATIVO",
        "sql": "stock = stock - ?  (sin stock>=)",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "movimientos.SALIDA_VENTA (tipo reutilizado)",
        "outbox": True,
        "offline_possible": True,
        "callers": (),
        "risk": "Cero llamadores. La UI de mezclas descuenta vía W03 "
                "(registrar_venta con componentes). Writer huérfano; sigue siendo riesgo.",
        "kind": "direct",
    },
    {
        "id": "W16",
        "file": "local_server.py",
        "function": "LocalFerreteriaAPI.create_sale",
        "business": "venta POS LAN",
        "sign": "-",
        "classification": "NEGATIVO",
        "sql": "stock = stock - ?  (sin stock>=)",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "movimientos.SALIDA_VENTA",
        "outbox": True,
        "offline_possible": True,
        "callers": ("services/local_api_client.py", "services/remote_adapters.py"),
        "risk": "Check de stock previo no atómico; puede ir negativo. Paralelo a W03.",
        "kind": "direct",
    },
    {
        "id": "W17",
        "file": "services/ventas_service.py",
        "function": "VentasService.editar_linea_factura",
        "business": "editar cantidad de línea de factura",
        "sign": "+/- (dif_cant = nueva - anterior)",
        "classification": "MIXTO",
        "sql": "stock = stock - ?  (dif_cant; bajar cantidad suma stock)",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": None,
        "outbox": False,
        "offline_possible": True,
        "callers": ("ui/dashboard_ui.py",),
        "risk": "1E.2: extraído de dashboard. Sin kardex. Sin outbox. Sin piso stock>=. Default legacy.",
        "kind": "direct",
    },
    {
        "id": "W18",
        "file": "services/ventas_service.py",
        "function": "VentasService.eliminar_linea_factura",
        "business": "quitar línea de factura",
        "sign": "+",
        "classification": "POSITIVO",
        "sql": "stock = stock + ?",
        "transaction": True,
        "updates_productos_stock": True,
        "kardex": "DELETE movimientos (no asiento inverso)",
        "outbox": False,
        "offline_possible": True,
        "callers": ("ui/dashboard_ui.py",),
        "risk": "1E.2: extraído de dashboard. DELETE de kardex. Sin outbox. Default legacy.",
        "kind": "direct",
    },
    {
        "id": "D01",
        "file": "local_first_db.py",
        "function": "enqueue_entity",
        "business": "outbox snapshot LWW",
        "sign": "n/a",
        "classification": "DERIVADO",
        "sql": "SELECT * FROM productos (payload incluye stock); no SET stock",
        "transaction": False,
        "updates_productos_stock": False,
        "kardex": None,
        "outbox": True,
        "offline_possible": True,
        "callers": ("repositories/_outbox.py", "services/ventas_service.py"),
        "risk": "Publica stock como campo LWW. No es autoridad.",
        "kind": "derived",
    },
    {
        "id": "D02",
        "file": "local_sync.py",
        "function": "SupabaseSyncService._upsert / build_remote_upsert_sql",
        "business": "push remoto LWW",
        "sign": "n/a",
        "classification": "DERIVADO",
        "sql": "ON CONFLICT (local_id) DO UPDATE SET … stock=EXCLUDED.stock",
        "transaction": False,
        "updates_productos_stock": False,
        "kardex": None,
        "outbox": False,
        "offline_possible": False,
        "callers": ("local_sync.py",),
        "risk": "Pisa stock remoto en PRE_CUTOVER. En AUTHORITATIVE se excluye stock del UPSERT.",
        "kind": "derived",
    },
    {
        "id": "D03",
        "file": "local_sync.py",
        "function": "SupabaseSyncService.pull_from_remote",
        "business": "pull LWW sobre SQLite local",
        "sign": "n/a",
        "classification": "DERIVADO",
        "sql": "UPSERT local de todas las columnas (incluye stock)",
        "transaction": False,
        "updates_productos_stock": True,
        "kardex": None,
        "outbox": False,
        "offline_possible": False,
        "callers": ("main.py",),
        "risk": "Pisa stock local con snapshot remoto (INV-02).",
        "kind": "derived",
    },
    {
        "id": "D04",
        "file": "repositories/_outbox.py",
        "function": "encolar / encolar_borrado",
        "business": "wrapper de outbox",
        "sign": "n/a",
        "classification": "DERIVADO",
        "sql": "no muta stock; traga excepciones",
        "transaction": False,
        "updates_productos_stock": False,
        "kardex": None,
        "outbox": True,
        "offline_possible": True,
        "callers": ("repositories/*.py", "services/*.py"),
        "risk": "Fallo de cola no aborta la TX de stock (INV-13).",
        "kind": "derived",
    },
    {
        "id": "D05",
        "file": "inventory_cutover.py",
        "function": "project_local_stock",
        "business": "proyección post-APPLY de inventory_balances",
        "sign": "n/a",
        "classification": "DERIVADO",
        "sql": "UPDATE productos SET stock = ? WHERE local_id = ?",
        "transaction": False,
        "updates_productos_stock": True,
        "kardex": None,
        "outbox": False,
        "offline_possible": False,
        "callers": ("inventory_gateway.py",),
        "risk": "Caché reconstruible. No es autoridad. No participa LWW post-cutover.",
        "kind": "derived",
        "scan_sql": True,
    },
)

UI_ENTRADA_COMPRA_DISPATCHERS: Tuple[dict, ...] = (
    {
        "id": "U01",
        "file": "ui/movimientos_ui.py",
        "function": "alta con tipo ENTRADA_COMPRA",
        "dispatches_to": "W10",
        "notes": "Combo de tipos incluye ENTRADA_COMPRA.",
    },
    {
        "id": "U02",
        "file": "ui/entrada_inventario_ui.py",
        "function": "combo tipo_movimiento",
        "dispatches_to": "W12",
        "notes": "addItems incluye ENTRADA_COMPRA.",
    },
    {
        "id": "U03",
        "file": "ui/productos_ui.py",
        "function": "guardar producto (stock=stock_total)",
        "dispatches_to": "W09/W08",
        "notes": "Caller de crear_producto/actualizar_producto; no UPDATE directo.",
    },
)

PRODUCTIVE_WRITER_FILES: Tuple[str, ...] = (
    "services/ventas_service.py",
    "repositories/compras_repo.py",
    "local_server.py",
    "services/movimientos_service.py",
    "repositories/inventario_repository.py",
    "services/mezclas_service.py",
    "ui/dashboard_ui.py",
    "repositories/productos_repo.py",
)

# Archivos de producción que contienen `UPDATE productos … stock`.
UPDATE_STOCK_FILES: FrozenSet[str] = frozenset(
    w["file"] for w in STOCK_WRITERS if w["kind"] == "direct"
)

# INSERT de stock inicial (no es UPDATE, se rastrea aparte).
INSERT_STOCK_FILES: FrozenSet[str] = frozenset(
    w["file"] for w in STOCK_WRITERS if w["kind"] == "insert"
)

DIRECT_STOCK_WRITER_FILES: FrozenSet[str] = UPDATE_STOCK_FILES | INSERT_STOCK_FILES

PROJECTION_STOCK_FILES: FrozenSet[str] = frozenset(
    w["file"] for w in STOCK_WRITERS if w.get("scan_sql")
)

# Publicación LWW del snapshot de stock.
SYNC_STOCK_SNAPSHOT_FILES: FrozenSet[str] = frozenset(
    w["file"] for w in STOCK_WRITERS if w["kind"] == "derived"
)

CLASSIFICATION_COUNTS = {
    "NEGATIVO": sum(1 for w in STOCK_WRITERS if w["classification"] == "NEGATIVO"),
    "POSITIVO": sum(1 for w in STOCK_WRITERS if w["classification"] == "POSITIVO"),
    "MIXTO": sum(1 for w in STOCK_WRITERS if w["classification"] == "MIXTO"),
    "DERIVADO": sum(1 for w in STOCK_WRITERS if w["classification"] == "DERIVADO"),
    "UNKNOWN": sum(1 for w in STOCK_WRITERS if w["classification"] == "UNKNOWN"),
}

# 1E.1: writers negativos preparados para gateway. SQL legacy sigue permitido
# mientras el cutover esté OFF. Cualquier UPDATE/INSERT de stock en una
# función no inventariada es UNTRACKED_DIRECT_WRITER.
NEGATIVE_WRITER_IDS = ("W03", "W16", "W06", "W02", "W15")
POSITIVE_WRITER_IDS = ("W01", "W04", "W05", "W09", "W18")
MIXED_WRITER_IDS = ("W07", "W08", "W10", "W11", "W12", "W13", "W14", "W17")
DIRECT_WRITER_IDS = tuple(
    w["id"] for w in STOCK_WRITERS if w["kind"] in ("direct", "insert")
)
GATEWAY_PREPARED_IDS = frozenset(DIRECT_WRITER_IDS)
DEPRECATED_WRITER_IDS = frozenset({"W15"})
# W04 no tiene caller de UI (el botón POS vacía el carrito). Permanece preparado.
W04_NO_UI_CALLER = True
PRE_CUTOVER_SQL_ALLOWED = "LEGACY_ALLOWED_PRE_CUTOVER"
UNTRACKED_DIRECT_WRITER = "UNTRACKED_DIRECT_WRITER"

AUTHORITATIVE_TIPO_BY_WRITER = {
    "W01": "COMPRA",
    "W02": "AJUSTE",
    "W03": "VENTA",
    "W04": "DEVOLUCION",
    "W05": "DEVOLUCION",
    "W06": "VENTA",
    "W07": "AJUSTE",
    "W08": "AJUSTE",
    "W09": "AJUSTE",
    "W10": "mapped",
    "W11": "AJUSTE",
    "W12": "mapped",
    "W13": "AJUSTE",
    "W14": "AJUSTE",
    "W15": "VENTA",
    "W16": "VENTA",
    "W17": "AJUSTE",
    "W18": "DEVOLUCION",
}
